# Generated by Django 2.2.4 on 2022-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
