# Generated by Django 2.2.4 on 2022-09-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20220925_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='User',
        ),
    ]
