# Generated by Django 2.2.4 on 2022-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20221001_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
