# Generated by Django 2.2.4 on 2022-09-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20220925_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='duration',
            new_name='age',
        ),
    ]
