# Generated by Django 2.2.4 on 2022-10-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LR', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegUser',
            new_name='Users',
        ),
    ]
