# Generated by Django 2.2.4 on 2022-10-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_LR', '0003_comments_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='message_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='user_id',
            new_name='user',
        ),
    ]
