# Generated by Django 2.2.4 on 2022-10-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('reason', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('planted_by', models.ForeignKey(null=True, on_delete='cascade', related_name='planted', to='app_exam.Users')),
            ],
        ),
    ]
