# Generated by Django 2.2.4 on 2022-10-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favBooksApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete='cascade', related_name='books_uploaded', to='favBooksApp.Users')),
                ('users', models.ManyToManyField(related_name='liked_books', to='favBooksApp.Users')),
            ],
        ),
    ]
