# Generated by Django 2.2.4 on 2022-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favBooksApp', '0002_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
